### ISSUE TITLE
logout

### ISSUE THREAD

**Issue by gioado7** [Freeuni-OOP/freeuni-hub#71]
დასაფიქსია logout-ის პროცესი, მაგალითად როცა იუზერი გავა პროფილიდან, საჭიროა უკან ისრით დაბრუნებისას ვერ მოახერხოს საკუთარ ფეიჯზე დაბრუნება.

**Comment by lukamacho** [comment]
http://csharpdotnetfreak.blogspot.com/2009/04/disable-browser-back-button-javascript.html

**Comment by lukamacho** [comment]
ამ ლინკზე წერია , რომ შეგვიძლია უკან დაბრუნების ისარი გავაუქმოთ და მოგვარდება ეგ პრობლემა.

**Comment by gioado7** [comment]
საინტერესოა, მომწონს მეც ეს იდეა
